#! /bin/sh

### SCREEN SETUP ###

sh $HOME/.config/screenlayout/screens.sh

# Workspaces
bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-4 -d 4 5 6
bspc monitor DP-2 -d 7 8 9 10
 
# Window Settings

bspc config border_width 	        0
bspc config window_gap            15

# Colors 
bspc config focused_border_color  "#191919"
bspc config normal_border_color   "#191919"
bspc config presel_feedback_color "#4C4C4C"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true

### Window Rules ###

bspc rule -a Slack monitor=HDMI-0
bspc rule -a discord monitor=HDMI-0
bspc rule -a Thunderbird monitor=HDMI-0 desktop=2
bspc rule -a "Zoom Group Chat" state=floating
bspc rule -a dunst monitor=HDMI-0
bspc rule -a Virt-manager desktop=6
bspc rule -a Synergy desktop=6
bspc rule -a looking-glass-client desktop=5 state=fullscreen
bspc rule -a conky desktop=3 state=fullscreen

### Autostart Apps ###

# Key Daemon
sxhkd &

# Polybar
~/.config/polybar/launch.sh &

# Restore Xresources
xrdb -load ~/.Xresources &

# Background
nitrogen --restore &

# Notifications
dunst &

# Compositor
picom &

# Network Manager
# nm-applet &

# Handles cursor problem
xsetroot -cursor_name left_ptr &

# Load Bitmap Fonts
# xset +fp ~/.local/share/fonts &
# xset fp rehash &
# xset fp+ /usr/share/fonts/bitmap &

# App startups
~/.scripts/startup/workapps.sh &
xscreensaver -no-splash &

# xrdb merge $HOME/.Xresources

