#! /bin/sh

### SCREEN SETUP ###

sh $HOME/.config/screenlayout/screens.sh

sxhkd &

. "${HOME}/.cache/wal/colors.sh"

bspc HDMI-0 -d IV V VI
bspc DP-4 -d I II III
bspc DP-2 -d  VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "$color3"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color3"

bspc rule -a brave desktop='^2' state=floating

xrdb merge $HOME/.Xresources

feh --bg-fill $/HOME/.rsrc/wall.jpeg

sh $HOME/.config/polybar/launch.sh

picom
