return {
  {
		"nvim-treesitter/nvim-treesitter",
		-- build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile", "VeryLazy" },
		cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
		dependencies = {
			{
				"JoosepAlviste/nvim-ts-context-commentstring",
				opts = { enable_autocmd = false },
			},
			{ "nushell/tree-sitter-nu" },
		},
		opts = {
			indent = { enable = true },
			autopairs = { enable = true },
			auto_install = false,
			sync_install = false,
			query_linter = {
				enable = true,
				use_virtual_text = true,
				lint_events = { "BufWrite", "CursorHold" },
			},
			refactor = {
				highlight_definitions = {
					enable = true,
					-- Set to false if you have an `updatetime` of ~100.
					clear_on_cursor_move = true,
				},
			},
			ensure_installed = {
				"bash",
				"comment",
				"dockerfile",
				"elixir",
				"fennel",
				"fish",
				"gleam",
				"go",
				"gomod",
				"graphql",
				"heex",
				"html",
				"http",
				"hurl",
				"javascript",
				"json",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"nix",
				"norg",
				"org",
				"python",
				"regex",
				"ruby",
				"rust",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
			},
			-- disable = {
			-- 	"vimdoc",
			-- },
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = { "org" },
			},
		},
	},
}
